name: LoopIntegrals
version: "2020.04.22"
date: 2020-04-22
description: |
    Compute master integrals using commutative and noncommutative methods from computational algebraic geometry

authors:
    - name: Mohamed Barakat
      url: https://mohamed-barakat.github.io
    - name: Robin Brüser
      url: https://www.researchgate.net/scientific-contributions/2138634848_Robin_Brueser
    - name: Tobias Huber
      url: https://www.physik.uni-siegen.de/tp1/research/researchgroups/huber.html.en?lang=en
    - name: Jan Piclum
      url: https://www.researchgate.net/scientific-contributions/34408173_Jan_Piclum

maintainers:
    - name: Mohamed Barakat
      url: https://mohamed-barakat.github.io
    - name: Robin Brüser
      url: https://www.researchgate.net/scientific-contributions/2138634848_Robin_Brueser
    - name: Tobias Huber
      url: https://www.physik.uni-siegen.de/tp1/research/researchgroups/huber.html.en?lang=en
    - name: Jan Piclum
      url: https://www.researchgate.net/scientific-contributions/34408173_Jan_Piclum

GAP: ">= 4.9.1"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "MatricesForHomalg"
      version: ">= 2020.04.18"
      url: "https://homalg-project.github.io/homalg_project/MatricesForHomalg/"
    - name: "RingsForHomalg"
      version: ">= 2020.04.18"
      url: "https://homalg-project.github.io/homalg_project/RingsForHomalg/"

www: https://homalg-project.github.io/LoopIntegrals
readme: README.md
packageinfo: https://homalg-project.github.io/LoopIntegrals/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/homalg-project/LoopIntegrals/releases/download/v2020.04.22/LoopIntegrals-2020.04.22.tar.gz

abstract: |

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
keywords: |
    loop diagrams, generating vectors, syzygies, master integrals.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>BBHP20</span>]   <b class='BibAuthor'>Barakat, M., Brüser, R., Huber, T. and Piclum, J.</b>,
     <i class='BibTitle'>LoopIntegrals, Compute master integrals using commutative and noncommutative methods from computational algebraic geometry,
             Version 2020.04.22</i>
     (<span class='BibYear'>2020</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://homalg-project.github.io/LoopIntegrals">https://homalg-project.github.io/LoopIntegrals</a></span>.
    </p>
    

bibtex: |
    @misc{ LoopIntegrals2020.04.22,
      author =           {Barakat, M. and Br{\"u}ser, R. and Huber, T. and Piclum, J.},
      title =            {{LoopIntegrals}, Compute master integrals using commutative and noncommutative methods from computational algebraic geometry, {V}ersion 2020.04.22},
      month =            {Apr},
      year =             {2020},
      note =             {GAP package},
      howpublished =     {\href {https://homalg-project.github.io/LoopIntegrals} {\texttt{https://homalg-project.github.io/}\discretionary {}{}{}\texttt{LoopIntegrals}}},
      keywords =         {loop diagrams; generating vectors; syzygies; master integrals},
      printedkey =       {BBHP20}
    }

