name: LoopIntegrals
version: "2023.11-04"
license: "GPL-2.0-or-later"
date: 2023-11-08
description: |
    Compute master integrals using commutative and noncommutative methods from computational algebraic geometry

authors:
    - name: Mohamed Barakat
      url: https://mohamed-barakat.github.io/
    - name: Robin Brüser
      url: https://www.researchgate.net/scientific-contributions/2138634848_Robin_Brueser
    - name: Tobias Huber
      url: https://www.physik.uni-siegen.de/tp1/research/researchgroups/huber.html
    - name: Jan Piclum
      url: https://www.researchgate.net/scientific-contributions/34408173_Jan_Piclum

maintainers:
    - name: Mohamed Barakat
      url: https://mohamed-barakat.github.io/
    - name: Robin Brüser
      url: https://www.researchgate.net/scientific-contributions/2138634848_Robin_Brueser
    - name: Tobias Huber
      url: https://www.physik.uni-siegen.de/tp1/research/researchgroups/huber.html
    - name: Jan Piclum
      url: https://www.researchgate.net/scientific-contributions/34408173_Jan_Piclum

GAP: ">= 4.12.1"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "MatricesForHomalg"
      version: ">= 2023.11-01"
      url: "https://homalg-project.github.io/pkg/MatricesForHomalg"
    - name: "RingsForHomalg"
      version: ">= 2023.11-01"
      url: "https://homalg-project.github.io/pkg/RingsForHomalg"
    - name: "GradedRingForHomalg"
      version: ">= 2020.05.01"
      url: "https://homalg-project.github.io/pkg/GradedRingForHomalg"
    - name: "Modules"
      version: ">= 2021.03-04"
      url: "https://homalg-project.github.io/pkg/Modules"
    - name: "GradedRingForHomalg"
      version: ">= 2021.04-01"
      url: "https://homalg-project.github.io/pkg/GradedRingForHomalg"

www: https://homalg-project.github.io/pkg/LoopIntegrals
readme: README.md
packageinfo: https://homalg-project.github.io/LoopIntegrals/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/homalg-project/LoopIntegrals/releases/download/v2023.11-04/LoopIntegrals-2023.11-04.tar.gz
    - name: .zip
      url: https://github.com/homalg-project/LoopIntegrals/releases/download/v2023.11-04/LoopIntegrals-2023.11-04.zip

pdf: https://github.com/homalg-project/LoopIntegrals/releases/download/v2023.11-04/LoopIntegrals-2023.11-04-manual.pdf

abstract: |

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
keywords: |
    loop diagrams, generating vectors, syzygies, master integrals.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>BBHP08</span>]   <b class='BibAuthor'>Barakat, M., Brüser, R., Huber, T. and Piclum, J.</b>,
     <i class='BibTitle'>LoopIntegrals, Compute master integrals using commutative and noncommutative methods from computational algebraic geometry,
             Version 2023.11-04</i>
     (<span class='BibYear'>1-08</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://homalg-project.github.io/pkg/LoopIntegrals">https://homalg-project.github.io/pkg/LoopIntegrals</a></span>.
    </p>
    

bibtex: |
    @misc{ LoopIntegrals2023.11-04,
      author =           {Barakat,  M.  and  Br{\"u}ser,  R.  and  Huber, T. and
                          Piclum, J.},
      title =            {{LoopIntegrals},   Compute   master   integrals  using
                          commutative    and    noncommutative    methods   from
                          computational algebraic geometry, {V}ersion 2023.11-04},
      month =            {3-},
      year =             {1-08},
      note =             {GAP package},
      howpublished =     {\href
                          {https://homalg-project.github.io/pkg/LoopIntegrals}
                          {\texttt{https://homalg-project.github.io/}\discretionary
                          {}{}{}\texttt{pkg/}\discretionary
                          {}{}{}\texttt{LoopIntegrals}}},
      keywords =         {loop  diagrams;  generating  vectors; syzygies; master
                          integrals},
      printedkey =       {BBHP08}
    }

