version: 2.1
jobs:
  test:
    parameters:
      docker_image:
        type: string
    docker:
      - image: << parameters.docker_image >>:latest
    working_directory: ~/.gap/pkg/LoopIntegrals
    steps:
      - checkout
      - run: |
          sudo apt update
          sudo apt dist-upgrade -y
          sudo apt install -y texlive-latex-extra texlive-science curl
          cd ..
          git clone --depth 1 https://github.com/homalg-project/homalg_project
          cd LoopIntegrals
          TERM=dumb make ci-test
          bash <(curl -s https://codecov.io/bash)
workflows:
  version: 2
  commit:
    jobs:
      - test:
          docker_image: gapsystem/gap-docker
  nightly:
    triggers:
      - schedule:
          # 0:00 UTC = 1:00 CET = 2:00 CEST
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - test:
          docker_image: gapsystem/gap-docker-master
