name: Tests

on:
  push:
    branches:
      - "master"
      - "*-ci"
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  test:
    strategy:
      matrix:
        image: [gapsystem/gap-docker, gapsystem/gap-docker-master]
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.image }}
    steps:
      - uses: actions/checkout@v1
      - run: mkdir -p /home/gap/.gap/pkg/
      - run: sudo cp -a $GITHUB_WORKSPACE /home/gap/.gap/pkg/
      - run: sudo chown -R gap:gap /home/gap/.gap/pkg/
      - run: |
          export HOME="/home/gap"
          cd /home/gap/.gap/pkg/
          sudo apt update
          sudo apt dist-upgrade -y
          sudo apt install -y texlive-latex-extra texlive-fonts-extra
          git clone --depth 1 https://github.com/gap-packages/AutoDoc.git
          git clone --depth 1 https://github.com/homalg-project/homalg_project.git
          # set SOURCE_DATE_EPOCH for reproducible PDFs
          export SOURCE_DATE_EPOCH=0
          TERM=dumb make -C LoopIntegrals -j $(nproc) --output-sync ci-test
          cp ./LoopIntegrals/.codecov.yml ./
          curl -s https://codecov.io/bash | bash
          git config --global user.name "Bot"
          git config --global user.email "empty"
          cd LoopIntegrals
          CUR_SHA=$(git rev-parse --verify HEAD)
          if [ "${{ matrix.image }}" = "gapsystem/gap-docker" ] && [ "$CUR_SHA" = "$(git rev-parse origin/master)" ] && [ $(dirname "$GITHUB_REPOSITORY") = "homalg-project" ]; then \
            git worktree add gh-pages/ gh-pages || (echo "There was an error. Make sure there is a branch named 'gh-pages'. See https://github.com/homalg-project/PackageJanitor#error-there-was-an-error-make-sure-there-is-a-branch-named-gh-pages"; exit 1); \
            git checkout master; \
            ./make_dist.sh --token "${{ secrets.GITHUB_TOKEN }}"; \
          else \
            echo "Not making a release."; \
          fi
